/*
CY.SEND® OpenAPI Documentation

Testing CYSENDGiftCardAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package cysend

import (
	"context"
	"testing"

	openapiclient "github.com/pourcheragh/cysend-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_cysend_CYSENDGiftCardAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CYSENDGiftCardAPIService GetActive", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var giftCardCode string

		resp, httpRes, err := apiClient.CYSENDGiftCardAPI.GetActive(context.Background(), giftCardCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CYSENDGiftCardAPIService GetGiftCard", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var giftCardCode string

		resp, httpRes, err := apiClient.CYSENDGiftCardAPI.GetGiftCard(context.Background(), giftCardCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CYSENDGiftCardAPIService PutActive", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var giftCardCode string

		httpRes, err := apiClient.CYSENDGiftCardAPI.PutActive(context.Background(), giftCardCode).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
